services:
  ingest:
    build: .
    container_name: ingest-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:8092
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/iotdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
  consumer:
    build: ../iot-consumer-worker
    container_name: consumer-worker
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:8092
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/iotdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

networks:
  default:
    external:
      name: kafka_default
