spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    username: root
    url: jdbc:mysql://localhost:3306/iotdatabase?useSSL=true&requireSSL=false&createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: MySQL8Dialect

logging:
  level:
    org.springframework: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v1/api-docs

kafka:
  bootstrap-servers: localhost:9092
  topic: telemetry

server:
  port: 8080

